#!/bin/bash

dirname=$(dirname $0)
cd $dirname

if [ -z $1 ]; then
    port=8088
else
    port=$1
fi

if [ -z $2 ]; then
    page="/"
else
    page=/"$2"
fi

openOnBrowser()
{
    open http://localhost:$port"$page"
}

fromPhp()
{
    entrypoint="$dirname"/html/
    if [ -d "$dirname"/vendor ]; then
        echo Dependencies already installed
    else
        composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader
    fi

    # Port set à 8088 par défaut pour ne pas rentrer en conflit avec les cours
    openOnBrowser
    php -S localhost:$port -t "$entrypoint"
}

fromDocker()
{
    docker build -t tuto .
    docker stop TutoRunning || true
    docker rm TutoRunning || true
    openOnBrowser
    docker run -it -p $port:80 --name TutoRunning tuto
}

if [ -x /usr/local/bin/docker ]; then
    fromDocker
else
    fromPhp
fi

exit 0
